version: "1.0"

services:
  app:
    build: .
    container_name: simple-iam
    restart: on-failure
    ports:
      - "3005:3005"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      # TODO: fix this to use '127.0.0.1' instead of 'db'
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_TEST_NAME=${DB_TEST_NAME}
      - CLIENT_SECRET=${CLIENT_SECRET}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.4.4
    restart: on-failure
    container_name: simple-iam-db
    command: "--mysql-native-password=ON"
    ports:
      - "3006:3306"
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE:${DB_NAME}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge
