package main

import (
	"github.com/Manuel-Leleuly/simple-iam/initializers"
	"github.com/Manuel-Leleuly/simple-iam/routes"

	_ "github.com/Manuel-Leleuly/simple-iam/swagger"
)

func init() {
	initializers.LoadEnvVariables()
	initializers.ConnectToDB()
	initializers.SyncDatabase()
}

// @title 						Simple IAM
// @version 					1.0
// @description 				A simple IAM made by me
// @termsOfService 				http://swagger.io/terms/

// @license.name 				Apache 2.0
// @license.url 				https://www.apache.org/licenses/LICENSE-2.0.html

// @host 						localhost:3005

// @securityDefinitions.apikey 	ApiKeyAuth
// @in 							header
// @name 						Authorization
// @description 				use access token generated by the login endpoint

func main() {
	server := routes.GetRoutes()

	// why port 3005? That's a mystery even I can't answer
	err := server.Run(":3005")
	if err != nil {
		panic("[Error] failed to start Gin server due to: " + err.Error())
	}
}
